version: '3.3'

services: 
  # git
  git:
    build: ./git/
    image: git
    container_name: git
    hostname: git-ssh-server
    restart: unless-stopped
    ports:
      - 80:80
      - 22:22
    networks:
      - app-network
    volumes: 
      - ./git/vol/:/var/git
  queue:
    image: "redis:alpine"
    container_name: queue
    volumes:
      - ./data/queue:/data
    networks:
      - app-network
    ports:
      - 6379:6379
  worker-queue:
    build: ./worker-queue/
    image: worker-queue
    restart: always
    container_name: worker-queue
    volumes:
      - ./worker-queue:/var/www/worker-queue
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - REDIS_URL=queue
      - REDIS_PORT=6379
      - GIT_CONTAINER=git
      - PORT=3000
    links:
      - queue
    depends_on:
      - queue
    ports:
      - '3000:3000'
    command: sh -c 'npm i && npm run start'
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./setup/db:/setup
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data
  # adminer is a  GUI for database, do not use for production
  adminer:
    image: adminer
    container_name: adminer
    networks:
      - app-network
    restart: always
    ports:
      - 8080:8080



networks:
  app-network:
    driver: bridge

volumes:
  git-storage:
  git-data:
