# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import publickey_pb2 as publickey__pb2
import user_pb2 as user__pb2


class ManipulateKeysStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetKey = channel.unary_unary(
                '/git.ManipulateKeys/SetKey',
                request_serializer=publickey__pb2.Publickey.SerializeToString,
                response_deserializer=user__pb2.Username.FromString,
                )
        self.RevokeKey = channel.unary_unary(
                '/git.ManipulateKeys/RevokeKey',
                request_serializer=publickey__pb2.Publickey.SerializeToString,
                response_deserializer=user__pb2.Username.FromString,
                )


class ManipulateKeysServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManipulateKeysServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKey,
                    request_deserializer=publickey__pb2.Publickey.FromString,
                    response_serializer=user__pb2.Username.SerializeToString,
            ),
            'RevokeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeKey,
                    request_deserializer=publickey__pb2.Publickey.FromString,
                    response_serializer=user__pb2.Username.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'git.ManipulateKeys', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManipulateKeys(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/git.ManipulateKeys/SetKey',
            publickey__pb2.Publickey.SerializeToString,
            user__pb2.Username.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/git.ManipulateKeys/RevokeKey',
            publickey__pb2.Publickey.SerializeToString,
            user__pb2.Username.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
