# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publickey.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpublickey.proto\x12\x03git\x1a\nuser.proto\"&\n\tPublickey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t2e\n\x0eManipulateKeys\x12\'\n\x06SetKey\x12\x0e.git.Publickey\x1a\r.git.Username\x12*\n\tRevokeKey\x12\x0e.git.Publickey\x1a\r.git.Usernameb\x06proto3')



_PUBLICKEY = DESCRIPTOR.message_types_by_name['Publickey']
Publickey = _reflection.GeneratedProtocolMessageType('Publickey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'publickey_pb2'
  # @@protoc_insertion_point(class_scope:git.Publickey)
  })
_sym_db.RegisterMessage(Publickey)

_MANIPULATEKEYS = DESCRIPTOR.services_by_name['ManipulateKeys']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUBLICKEY._serialized_start=36
  _PUBLICKEY._serialized_end=74
  _MANIPULATEKEYS._serialized_start=76
  _MANIPULATEKEYS._serialized_end=177
# @@protoc_insertion_point(module_scope)
