# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_pb2 as user__pb2


class CreateUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatUeser = channel.unary_unary(
                '/git.CreateUser/CreatUeser',
                request_serializer=user__pb2.User.SerializeToString,
                response_deserializer=user__pb2.Username.FromString,
                )


class CreateUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatUeser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatUeser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatUeser,
                    request_deserializer=user__pb2.User.FromString,
                    response_serializer=user__pb2.Username.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'git.CreateUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatUeser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/git.CreateUser/CreatUeser',
            user__pb2.User.SerializeToString,
            user__pb2.Username.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
