# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import repo_pb2 as repo__pb2


class getCommitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getHeadCommit = channel.unary_unary(
                '/git.getCommit/getHeadCommit',
                request_serializer=repo__pb2.Repo.SerializeToString,
                response_deserializer=repo__pb2.Commit.FromString,
                )
        self.findAllCommits = channel.unary_unary(
                '/git.getCommit/findAllCommits',
                request_serializer=repo__pb2.Repo.SerializeToString,
                response_deserializer=repo__pb2.Commits.FromString,
                )


class getCommitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getHeadCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findAllCommits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getCommitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getHeadCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.getHeadCommit,
                    request_deserializer=repo__pb2.Repo.FromString,
                    response_serializer=repo__pb2.Commit.SerializeToString,
            ),
            'findAllCommits': grpc.unary_unary_rpc_method_handler(
                    servicer.findAllCommits,
                    request_deserializer=repo__pb2.Repo.FromString,
                    response_serializer=repo__pb2.Commits.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'git.getCommit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class getCommit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getHeadCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/git.getCommit/getHeadCommit',
            repo__pb2.Repo.SerializeToString,
            repo__pb2.Commit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def findAllCommits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/git.getCommit/findAllCommits',
            repo__pb2.Repo.SerializeToString,
            repo__pb2.Commits.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
