# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x03git\"&\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x18\n\x08Username\x12\x0c\n\x04name\x18\x01 \x01(\t24\n\nCreateUser\x12&\n\nCreateUser\x12\t.git.User\x1a\r.git.Usernameb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_USERNAME = DESCRIPTOR.message_types_by_name['Username']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:git.User)
  })
_sym_db.RegisterMessage(User)

Username = _reflection.GeneratedProtocolMessageType('Username', (_message.Message,), {
  'DESCRIPTOR' : _USERNAME,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:git.Username)
  })
_sym_db.RegisterMessage(Username)

_CREATEUSER = DESCRIPTOR.services_by_name['CreateUser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=19
  _USER._serialized_end=57
  _USERNAME._serialized_start=59
  _USERNAME._serialized_end=83
  _CREATEUSER._serialized_start=85
  _CREATEUSER._serialized_end=137
# @@protoc_insertion_point(module_scope)
